### ISSUE TITLE
Gumcast down?

### ISSUE THREAD

**Issue by ksbrar** [gumcast/gumcast-api#44]
Keep getting 200 responses.

**Comment by bcomnes** [comment]
429 Too Many Requests. Looks like It's getting rate limited.

**Comment by bcomnes** [comment]
I added caching a few months ago and that was working really well, but looks like it's time to take more measures.

**Comment by bcomnes** [comment]
Looks like its back up.

**Comment by ksbrar** [comment]
Yup, working for me - thanks!
